version: 2.1
orbs:
  node: circleci/node@4.7.0

jobs:
  build_dev:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install
      - run:
          name: Installing Python
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: npm install
      - save_cache:
          paths:
            - ~/project/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm run ci
      - run: cd dist; zip -r ../sigma18_dist.zip *
      - run: "curl -u $AUTH_TOKEN -f -X 'POST' \"https://$NODEPAD_HOST/api/apps/sigma18-dev/content/zip\" -H 'accept: application/json' -H 'Content-Type: multipart/form-data' -F 'bin=@sigma18_dist.zip;type=application/zip'"      
  
  build_prod:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: npm install
      - save_cache:
          paths:
            - ~/project/node_modules
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm run ci
      - run: cd dist; zip -r ../sigma18_dist.zip *
      - run: "curl -u $AUTH_TOKEN -f -X 'POST' \"https://$NODEPAD_HOST/api/apps/sigma18/content/zip\" -H 'accept: application/json' -H 'Content-Type: multipart/form-data' -F 'bin=@sigma18_dist.zip;type=application/zip'"      

workflows:
  cicd-workflow:
    jobs:
      - build_dev:
          filters:
              branches:
                only:
                  - develop
      - build_prod:
          filters:
              branches:
                only:
                  - master
